language: java
dist: xenial

sudo: required
addons:
   chrome: stable


services:
- xvfb
env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - sudo apt-get update
  - sudo apt-get install dbus-x11
  - sudo apt-get install libgconf-2-4
  - export DISPLAY=:99.0
  - sleep 3
  
  - export CHROME_BIN=/usr/bin/google-chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin

  
before_script:

- sudo apt-get install libnss3
- sudo apt-get --only-upgrade install google-chrome-stable
- sudo cp chromedriver /usr/local/bin/.
- sudo chmod +x /usr/local/bin/chromedriver

script: 

        - bash ./db_setup.sh
        - mvn clean
        - mvn -Dtest=TestDAO,TestCrud,TestAlumnoDBIntegrationInsert test
         
Notifications:
email:
    on_success: always
    on_failure: never